### ISSUE TITLE
Feature Request: When do I play <team name>

### ISSUE THREAD

**Issue by kmcgaire** [kmcgaire/MLSBBot#1]
Ask the bot when you play a certain team, and it will figure out the first game you play against <team name> from the list of subscriptions you currently have

**Comment by kmcgaire** [comment]
@robinsharma guy never even completed this....

**Comment by pablolleras** [comment]
useless

**Comment by robinsharma** [comment]
:crying_cat_face:

**Comment by robinsharma** [comment]
https://github.com/kmcgaire/MLSBBot/commit/99c4ed2adedbfb87b7b32445f7622d6382d1a1e8
